### ISSUE TITLE
Integration with AIM systems

### ISSUE THREAD

**Issue by esune** [bcgov/issuer-kit#216]
Using VCs for authentication/authorization purposes requires administrators to perform separate steps to add the appropriate roles to user profiles on the AIM system of choice, causing overhead.

We need a mechanism that allows to programmatically apply these changes on the target AIM system (e.g.: Keycloak), regardless of the architecture chosen.

Investigate the possibility of creating plugins that can be plugged at runtime to extend the basic functionality of Issuer Kit or, alternatively, using webhooks to deliver requests similarly to what aca-py does now with the controller.

**Comment by swcurran** [comment]
I was thinking of this in the reverse way. Is there a way in Keycloak to add a plugin that calls Issuer Kit (or invokes Issuer kit functionality) to offer a credential to a user when their Keycloak account gets created.  That would eliminate the separate Issuer Kit/Keycloak consoles.

**Comment by esune** [comment]
I need to further investigate how much "programming" can be done from within Keycloak. I am not aware of ways to "push" changes that happen in Keycloak out to other systems: as far as I know, it is delegated to the external system to use the APIs exposed by keycloak to figure out that something happened and act accordingly, dispatching requests to either Keycloak iteself or other resources.

This is why I was proposing a plugin/middleware or webhook delivery: this would abstract from the architecture of the AIM system and allow a custom piece of code that does what is necessary (e.g.: user creation, assigning/removing roles, etc.) when notified/triggered by Issuer Kit.

**Comment by swcurran** [comment]
Agreed.  This is a lower priority and I'm hoping that Todd can try to learn things to help us.  It's not clear how tied we want to be to Keycloak, so we really need to think about that.  For example, I think that the MoJ folks want to use the VC to enable access to systems other than Keycloak, so a tight Keycloak integration might not even need to be a high priority.  Or maybe they make it easy and so it is a light lift.  Either way, we do should not be a big effort on this.

**Comment by WadeBarnes** [comment]
I think it's best to keep the implementation separate from the aggregator (KeyCloak in this case), and use APIs and webhooks to perform the necessary integration.  That way we're not tied to one specific product.

**Comment by swcurran** [comment]
Yes -- if we did something specific for Keycloak, it would be a plugin for keycloak that used part of Issuer Kit as a dependency. And if keycloak supports that, others likely do.

The core identity kit should not have anything specific for Keycloak.
