### ISSUE TITLE
Update keycloak URLs for the various issuer-kit and vc-authn-oidc apps

### ISSUE THREAD

**Issue by swcurran** [bcgov/issuer-kit#234]
The change of URLs is covered in the SSO channel on Rocketchat and in a technical bulletin issued by Shared Services.

Please coordinate the update of the Verified Person issuer with IDIM (per related email) and the rest of the keycloak-based services.

**Comment by esune** [comment]
Affected services that will require updating:
- [ ] identity-kit TEST
- [ ] identity-kit PROD
- [ ] csb-audio-demo DEV
- [ ] csb-audio-demo TEST

I do not have access to the configurations for these, c.c.-ing @WadeBarnes 
- [ ] A2A DEV
- [ ] A@A TEST
- [ ] A@A PROD

All the services from the `essential-services-demo` repository are using direct authentication with `vc-authn` and will not need to be updated.

**Comment by WadeBarnes** [comment]
A2A updates are covered by https://justice.gov.bc.ca/jira/browse/A2A-43

**Comment by esune** [comment]
All environments are updated except for Issuer Kit: I will complete the update tomorrow contextually with the update to BCSC endpoints.

**Comment by esune** [comment]
All updates completed successfully.
