### ISSUE TITLE
Check for correct pres_req_conf_id in token

### ISSUE THREAD

**Issue by esune** [bcgov/issuer-kit#249]
When authenticating with `vc-authn`, the `issuer-web` application should be checking for the presence of a `pres_req_conf_id`  attribute  in the id token, whose value should match the value of the `pres_req_conf_id` query parameter submitted with the OIDC auth flow.

Basically:
- if authentication is enabled (check settings file)
- if additional query parameters are configured, and `pres_req_conf_id` is configured
- when validating the token response, the value of `pres_req_conf_id` in the token MUST match the value of the same parameter in the configuration

**Comment by wadeking98** [comment]
@esune what should the functionality be if they do not match? redirect to some URL?

**Comment by esune** [comment]
Same behaviour as when the [token guard](https://github.com/bcgov/issuer-kit/blob/master/issuer-web/src/router/guards/valid-token.ts) fails: I believe it throws an authentication error and redirects to the `/unauthorized` route.

**Comment by esune** [comment]
Fixed in #250
