### ISSUE TITLE
claim-config.json values are not updating

### ISSUE THREAD

**Issue by GStysis** [bcgov/issuer-kit#313]
Updating title fields in **claim-config.json** files don't update the website pages.

For example, I tried to test by editing the "First Name" title fields as seen in the screenshot below, but after running ./manage build and ./manage start, the website still shows "First Name"

![image](https://user-images.githubusercontent.com/43324856/127551521-fff3b77c-5853-4ab5-b5ce-73e92e217a0d.png)

I also tried first removing the old containers in docker in case they were being reused and not updated by calling:

docker rm issuer-kit_issuer-admin_1
docker rm issuer-kit_issuer-web_1

And then rerunning the build and start commands

**Comment by esune** [comment]
Your browser might be caching the content, please try clearing the cache and/or force-refreshing the page to see the new config.

The Caddy webserver should be able to detect the file was updated and serve the new one, but sometimes the browser still doesn't refresh the cached content - unfortunately.

**Comment by GStysis** [comment]
Awesome clearing my cache worked perfectly. Thanks for the quick help, and your work on this solution!
