### ISSUE TITLE
Bypassing the email invitation and redirecting automatically to issuer-web: terms and conditions page

### ISSUE THREAD

**Issue by GStysis** [bcgov/issuer-kit#314]
Is it possible to bypass the email invitation for a new invite and redirect the browser directly to the issuer-web terms and conditions page after the issuer clicks on the "save" button on the invite page?

I was able to find the new invite's token via context.data.token in the api>src directory but was wondering if there is some "get" method which can be called from issuer-admin's DataCollection.vue to collect this token string from the server side. If so I would be able to call window.location.href from the validateAndSave method and redirect automatically.

Thanks

**Comment by WadeBarnes** [comment]
@esune, are you able to help with this?

**Comment by esune** [comment]
This is not the way the application was designed: the admin interface is only supposed to be used to manage invitations (create, update, delete) so this is why there is no redirect to `issuer-web` from there, they're two completely separate components.

If you want to disable token validation you can change the application settings to do so, see [the docs](https://github.com/bcgov/issuer-kit/blob/master/docs/ConfiguringIssuerKit.md).

Additionally, the API service exposes a swagger endpoint at `http://localhost:3030/swagger/docs/` you could use to fetch the invite information - including the token, if you were to integrate the admin/api functionality with external back end systems (they're the same endpoints used by `issue-admin` btw).
