### ISSUE TITLE
Add support for an Overlays Capture Architecture (OCA) bundle in Issuer Kit

### ISSUE THREAD

**Issue by swcurran** [bcgov/issuer-kit#370]
OCA is a method for providing semantic and display information about a credential to any app using that credential -- e.g. multi-lingual labels, information pop-ups for more information on field, code/label pairs for dropdowns, etc.

It would be nice to add OCA to Issuer Kit as a method for learning about how to use the technology.

**Comment by esune** [comment]
@swcurran are there relevant links you could add to the ticket as resources to evaluate what needs to be implemented?

**Comment by swcurran** [comment]
I'll add more if/when we decide to do this project. I was just putting this out there as a backlog item.

A website about OCA is here: https://oca.colossi.network/
