### ISSUE TITLE
POST /schemas endpoint returning 400

### ISSUE THREAD

**Issue by wadeking98** [bcgov/issuer-kit#381]
## Behavior:  
In the new ACAPY release (`aries-cloudagent:py36-1.16-1_0.7.4`), when pushing a schema that already exists to the ledger through the /schemas endpoint, the agent now returns a 400 error and says that the schema is already on the ledger. 
## Expected Behavior:  
In previous versions of acapy, (up to `aries-cloudagent:py36-1.16-1_0.7.3`), when pushing a schema that already exists to the ledger through the /schemas endpoint, the agent responds with a 200 status code and responds with the id of the existing schema on the ledger.
## Issue:  
The new acapy functionality on the /schemas endpoint breaks issuer-kit. The issuer-kit-api starts by loading the schemas from the config file and sending them to the issuer-kit-agent. Since the acapy now responds with a 400 error if the schemas already exist, this causes the API to error out.
## Possible Solutions:  
- Rollback to version `aries-cloudagent:py36-1.16-1_0.7.3`
- Update ACAPY to respond with schema id if it already exists on the ledger
- Make the issuer-kit-api search for a schema id on the ledger first and only send a schema to the ledger if it does not already exist

**Comment by wadeking98** [comment]
@swcurran what are your thoughts on the possible solutions?

**Comment by swcurran** [comment]
Is the schemaId needed by issuer kit?  Is it not persisted somewhere? What is it needed for?

Rolling back could be used if this is urgent, for current deployments, but ultimately we have to move forward ASAP.

I’ll find the ACA-Py issue and find it about the change. I recall the devs discussing this and coming to what was thought to be a reasonable conclusion.

**Comment by wadeking98** [comment]
Okay, I can figure out a solution on the issuer-kit side. The ACA-Py functionality seems reasonable and I assume the devs changed the functionality for a good reason
