### ISSUE TITLE
Bugs when trying to run in demo mode

### ISSUE THREAD

**Issue by finnformica** [bcgov/issuer-kit#422]
Hi all,

I am trying to get an issuer service up and running to work with a vc-authn-oidc service. I am using an M1 Macbook Pro and have had previous problems with using tools by bcgov and Hyperledger with this setup. I am attempting to run the `issuer-kit` in demo mode by first running `ngrok/start-ngrok.sh` (which was successful) and then running `docker/manage build` which was unsuccessful. When the docker failed to build I got the following error:

```
Building issuer-kit-api image using quay.io/fedora/nodejs-18 as base...
error: Unable to load docker config: json: cannot unmarshal string into Go value of type docker.dockerConfig
FATAL: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

which is strange since my docker daemon is up and running a local version of Keycloak. I have a feeling that this is linked to this issue [here](https://github.com/bcgov/vc-authn-oidc/issues/302). Any help with this problem would be much appreciated thank you!

**Comment by WadeBarnes** [comment]
You are correct.  This project's manage script uses `s2i` for some of the builds.  I'll discuss with @esune directly, as I don't have a Mac I can use for testing.

**Comment by esune** [comment]
@finnformica could you try the code from my PR (see #423)? I was able to run on M1 mac without issues. The version of `s2i` currently installed on my machine is `v1.3.8-dirty` (the latest available on `brew`).

**Comment by finnformica** [comment]
@esune I've seen that its been merged so I've run a `git pull` to update my local repo. I've then run `brew uninstall source-to-image` and `brew install source-to-image` as I tried `brew install source-to-image@1.3.8-dirty` but brew failed to find the version. Running `s2i version` confirms I have `v1.3.8-dirty` as well.

With the update repo I ran `./manage build` and still recieve the same error:

```
Building issuer-kit-api image using quay.io/fedora/nodejs-18 as base...
error: Unable to load docker config: json: cannot unmarshal string into Go value of type docker.dockerConfig
FATAL: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Sorry for the long answer I just wanted to recount my steps since you said its working for you but it doesn't seem like anything has changed on my end.

**Comment by esune** [comment]
@finnformica could you check if tehre are updates for your docker installation and paste the result of `docker --version`?
If possible, I'd also try the "purge" command (it will remove all running containers) to clean up the daemon settings/cache. The error really seems to indicate the shell cannot connect to the daemon and I wasn't able to reproduce it unfortunately.

**Comment by finnformica** [comment]
@esune my docker version is `Docker version 24.0.2, build cb74dfc`

I couldn't find the purge command did you mean `docker system prune`?

**Comment by finnformica** [comment]
@esune even after purging the containers and data annoyingly I still get the same error...
