### ISSUE TITLE
Incomplete Issuer Flow development

### ISSUE THREAD

**Issue by sebagroh** [bcgov/issuer-kit#426]
As the documentation says on: https://github.com/bcgov/issuer-kit/blob/main/docs/issuer-kit.md On completion, display a link to a demo site so the user can try their new verifiable credential. The test issuer has a link to [CBS Audio](https://csb-audio.pathfinder.gov.bc.ca/) that seems to be non existent. Thoughts? Exists some URL to test the credential?

**Comment by esune** [comment]
@sebagroh we don't currently have a hosted service that can be used to verify the issued credential. We should probably remove the link to CSB Audio as it was a specific use-case.

You could potentially use https://github.com/bcgov/vc-authn-oidc (I would suggest using the `2.0-development` branch as the `1.0` release is at end of support) with an appropriately-configured proof request.

**Comment by esune** [comment]
Closing, please feel free to reopen if necessary
