### ISSUE TITLE
Agent not ready stuck

### ISSUE THREAD

**Issue by SuryaSHalwasia** [bcgov/issuer-kit#433]
I'm facing this same issue. Its stuck in an endless loop of agent not ready even for the demo mode. The von network is working fine. I tried it with a blank clone of the repository and facing the same issue. Kindly help. It was working fine earlier but suddenly getting these errors.

<img width="958" alt="Screenshot 2024-01-08 224601" src="https://github.com/bcgov/issuer-kit/assets/118595736/9060aaf3-ea51-4770-8d4e-eaa3b47d73af">

**Comment by esune** [comment]
It looks like you possibly provided more than one value for the seed on different runs, based on the error. Try running `./manage rm` before you run `./manage start` again.

**Comment by SuryaSHalwasia** [comment]
Thank you so much. That worked for me.
