### ISSUE TITLE
Issuer-app unauthorized 

### ISSUE THREAD

**Issue by SuryaSHalwasia** [bcgov/issuer-kit#434]
I am unable to access the issuer-app running on localhost 8082. When I try to issue credentials through admin portal I am able to open the link till I receive this QR code
<img width="596" alt="web-app" src="https://github.com/bcgov/issuer-kit/assets/118595736/f7a873f6-bedf-4a8c-bb14-2fba5d08c1f1">

The QR code points to a link to the app of the form http://localhost:8082/?c_i=eyJAdHlwZSI6ImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztz==
When I try to again open this link in my browser, I receive unauthorized.
<img width="913" alt="unauthorized" src="https://github.com/bcgov/issuer-kit/assets/118595736/975d69fb-1ef5-4cba-9d19-1061b30841c9">

Kindly help. Thank you.

**Comment by esune** [comment]
As per button label, you need to use a digital wallet to scan the QR code: https://github.com/bcgov/issuer-kit/blob/main/docs/GettingApp.md
