### ISSUE TITLE
Unable to start development mode

### ISSUE THREAD

**Issue by vanshviggg** [bcgov/issuer-kit#438]
I am unable to start development mode. When I try to run with npm install and without mange build I get an error and issuer-admin doesn't start. 
<img width="701" alt="error2" src="https://github.com/bcgov/issuer-kit/assets/156162584/68507a77-9cf7-42aa-8e07-edc4d26645d7">

And when I run the manage build command get this error. 
<img width="848" alt="error" src="https://github.com/bcgov/issuer-kit/assets/156162584/60cd7ba5-7d2b-4426-8834-529e9d03e41c">

Kindly help. 
Thanks.

**Comment by esune** [comment]
Have you tried using `./manage start-dev` for development mode? https://github.com/bcgov/issuer-kit/blob/edee62127449f125ae428587f09087bcf9722f7b/docker/manage#L138-L139

**Comment by vanshviggg** [comment]
Yes, I used the start-dev command. I received this error when I did npm install and without the manage build command. When I started the manage build command the build crashed with permission errors.
<img width="947" alt="error-dev" src="https://github.com/bcgov/issuer-kit/assets/156162584/5e229243-09a9-436d-8ec3-abb858af4e18">

**Comment by esune** [comment]
I would have to take a look again as it's been some time, however it *should* work with `start-dev` if you:
* run `npm install` for all the three apps (`api`, `issuer-admin` and `issuer-web`) on your host machine, to populate `node_modules`
* run `./manage start-dev`

What does your Docker setup look like? Are you using WSL2?

**Comment by vanshviggg** [comment]
I'm using GitBash. I have run the npm install in the three directories. Still getting this error

**Comment by esune** [comment]
> I'm using GitBash. I have run the npm install in the three directories. Still getting this error

Can you provide details on your Docker setup please?

**Comment by vanshviggg** [comment]
> > I'm using GitBash. I have run the npm install in the three directories. Still getting this error
> 
> Can you provide details on your Docker setup please? Are you using WSL2 engine or Hyper-V?

I'm using WSL2 engine.

**Comment by esune** [comment]
Unable to reproduce on Win11 using WSL2 as Docker back-end following the appropriate steps:
- Start an instance of [von-network](https://github.com/bcgov/von-network)
- Run `npm install` for all components: `api`, `issuer-admin`, `issuer-web`
- Run `./manage build` from the `docker` folder
- Run `./manage start-dev` from the docker folder - it will take some time on first start for the web frontends to be ready

Please feel free to reopen if the problem persists and more information can be provided for troubleshooting.
